### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by acidjunk** [ing-bank/zkrangeproof#11]
I think this project needs a license before it can be used.

**Comment by acidjunk** [comment]
The article on https://www.ingwb.com/themes/blockchain-articles/ing-launches-major-addition-to-blockchain-technology states it will be a Open Source license, but to make it official I think you need to choose one explicitly (e.g. MIT, GPLv3 etc.): 

"ING has launched ZKRP as an open source solution, which means that other interested parties in the development community are able to download, access and even contribute to the solution, which allows for greater testing and can lead to improvements."

**Comment by ArthurManz** [comment]
Hi @acidjunk thanks for the heads up :+1:. We just added our License file.
