### ISSUE TITLE
ZKSM? 

### ISSUE THREAD

**Issue by sirpy** [ing-bank/zkrangeproof#13]
In the paper it says there's also implementation for zero knowledge set membership, but I can't find it.

**Comment by sirpy** [comment]
any one?

**Comment by eduardomoraesdemorais** [comment]
See file ccs08.go

**Comment by ArthurManz** [comment]
Hi @sirpy could you find the ZKSM code? Please let us know if you have any questions. We are working on improving our use case examples and repository structure. :smile: 

Here is the file @eduardomoraesdemorais refered to: 
https://github.com/ing-bank/zkrangeproof/blob/master/go-ethereum/zkrangeproof/ccs08.go
