### ISSUE TITLE
Installation or developers guide would be helpful

### ISSUE THREAD

**Issue by ice09** [ing-bank/zkrangeproof#4]
It would help a lot for new devs if there was one of:

- Installation Guide
- Setup
- Walkthrough
- Tutorial

In the current state, it's difficult to see how the precompiled contracts can be called and how the included Geth version is supposed to be used, a real-life example would be great.

**Comment by stijnmeijer** [comment]
Hi ice09, thanks a lot for pointing this out! We added some usage instructions to the README.md file in e0bc76c79ad512ee6626d9d1280c850736d631c3. Please let us know if anything remains unclear.
