### ISSUE TITLE
Efficient Zero-Knowledge Range Proofs in Ethereum - Next Steps? 

### ISSUE THREAD

**Issue by nathanawmk** [ing-bank/zkrangeproof#7]
Hi all,

I am Nathan Aw from Singapore and I work on blockchain technologies within the financial sector. 

I read the amazing paper ("Efficient Zero-Knowledge Range Proofs in
Ethereum") written by this team. May I know whether this project will be continued. If yes, what will be the roadmap and future directions? 

Thank you!

Regards,

Nathan Aw
https://sg.linkedin.com/in/awnathan
https://sg.linkedin.com/in/awnathan/zh-cn

**Comment by ArthurManz** [comment]
Thanks for your interest @nathanawmk . We are preparing a documentation website and we will add there the roadmap. Right now we are working on Bulletproofs. :rocket:
